trigger: 
  - akhil

variables:
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      name: TemplatesForAzurePipelines
      ref: refs/heads/master
      type: git

stages:
  - template: librarymanagementsystem/stages/frontend.yaml@templates
  # - template: librarymanagementsystem/stages/backend_books.yaml@templates 
  # - template: librarymanagementsystem/stages/backend_users.yaml@templates

  


  

