name: Trivy Scan 

on: push
 
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building the images
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lsm_frontend:${{ github.run_id }} ./frontend/library-store/

      - name: Run Trivy Scan
        id: trivy-scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 1 --severity CRITICAL ${{ secrets.DOCKER_USERNAME }}/lsm_frontend:${{ github.run_id }}
        continue-on-error: true

      - name: Check Trivy Results
        if: steps.trivy-scan.outcome == 'failure'
        run: |
          echo "Critical vulnerabilities found in the Docker image. Stopping workflow."
          exit 0
      
      - name: Deploy Application
        if: success() 
        run:  echo "Deploying application..."        
        
      - name: Pushing the image to the DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lsm_frontend:${{ github.run_id }}             